name: 'dbt_finance'
version: '1.0.0'
config-version: 2

# Profile must match the top-level key in profiles.yml
profile: 'finance_analysis_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_finance:
    # Staging models - materialized as views
    staging:
      +materialized: view
      +schema: staging
    
    # Marts - materialized as tables
    marts:
      +materialized: table
      +schema: analytics
